// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSu_FWVYQVRq2QCEJwh9s4_EgKkuD6Po',
    appId: '1:159908810348:android:89ce2c040f46cc896b9249',
    messagingSenderId: '159908810348',
    projectId: 'contaorganiza-381bb',
    storageBucket: 'contaorganiza-381bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9uqfiRyEPVoeKcS_FGE42c1NfHmYpC8',
    appId: '1:159908810348:ios:6821e3ff95d670d86b9249',
    messagingSenderId: '159908810348',
    projectId: 'contaorganiza-381bb',
    storageBucket: 'contaorganiza-381bb.appspot.com',
    iosBundleId: 'ContaOrganiza.contaOrganiza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdpQD1XTroFZLqxLT9hpEpsjxNvuhzljM',
    appId: '1:159908810348:web:26a164e50f0855146b9249',
    messagingSenderId: '159908810348',
    projectId: 'contaorganiza-381bb',
    authDomain: 'contaorganiza-381bb.firebaseapp.com',
    storageBucket: 'contaorganiza-381bb.appspot.com',
    measurementId: 'G-LYDQMN51M4',
  );
}
