name: conta_organiza
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11  # Certifique-se de usar a versão mais recente
  cupertino_icons: ^1.0.6
  reorderable_grid_view: ^2.0.3
  file_picker: ^5.0.0
  image_picker: ^0.8.4+4
  intl: ^0.18.1 # Adicione esta linha
  shared_preferences: ^2.0.9
  firebase_core: ^2.5.0 # Verifique a versão mais recente no pub.dev
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.7.6
  firebase_app_check: ^0.2.2+6
  google_sign_in: ^5.4.2
  flutter_localizations: # Adicione esta linha
    sdk: flutter
  flutter_pdfview: ^1.0.4
  dio: ^4.0.6
  open_file: ^3.2.1
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  url_launcher: ^6.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf